### ISSUE TITLE
cutechess-cli problems

### ISSUE THREAD

**Issue by ppigazzini** [ianfab/fishtest#1]
@ianfab cutechess-cli Windows and Linux are linked dynamically.
Windows version is missing some dll (e.g. api-ms-win-crt-runtime-l1-1-0.dll).
Linux version requires a very recent libgcc (only Ubuntu 16.10 works) 

Here is the Windows static cutechess-cli.exe 32 bit (for max compatibility); in this way no ddl is required (Qt5Core.dll and *140.dll):
[cutechess-cli.zip](https://github.com/ianfab/fishtest/files/819987/cutechess-cli.zip)

Instructions to built the static cutechess-cli.exe 32 bit:
1. install MSYS2:
http://www.msys2.org/
  a. start the installer
  b. update with the command:
  pacman -Syuu
2. start a MSYS2 MinGW 32 bit console (not 64 bit)
3. start these commands (it takes several minutes)
pacman -S git make mingw-w64-i686-gcc mingw-w64-i686-jasper mingw-w64-i686-qt5-static
git clone https://github.com/cutechess/cutechess.git
cd cutechess
C:/msys32/mingw32/qt5-static/bin/qmake.exe -config release
make
strip projects/cli/cutechess-cli.exe

**Comment by ianfab** [comment]
@ppigazzini Thanks. Could you please open a pull request with an updated version of `cutechess-cli-win.zip` in https://github.com/ianfab/FishCooking?

**Comment by ppigazzini** [comment]
@ianfab opened

**Comment by ianfab** [comment]
Thank you.

**Comment by ppigazzini** [comment]
@ianfab I opened a pull request with the updated version of cutechess-cli-linux-32bit.zip and cutechess-cli-linux-64bit.zip, built with Qt5 static.
Tested working with Ubuntu 14.04 16.04 16.10, CentOS7 (devtoolset-6), Bash on Ubuntu on Windows.

**Comment by ianfab** [comment]
Thanks, I merged the PR. Since all three compiles are linked statically now, I think I can close this.

**Comment by ppigazzini** [comment]
Already closed :)
