### ISSUE TITLE
Variant cmd exit tasks

### ISSUE THREAD

**Issue by Nordlandia** [ianfab/fishtest#16]
Okey so i decided to contribute again to variant framework but this text implies something is wrong in the settings. 

Exception running games:
Traceback (most recent call last):
  File "C:\fishtest-master\worker\worker.py", line 88, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "C:\fishtest-master\worker\games.py", line 370, in run_games
    setup_engine(new_engine, worker_dir, sha_new, repo_url, worker_info['concurrency'])
  File "C:\fishtest-master\worker\games.py", line 128, in setup_engine
    subprocess.check_call(MAKE_CMD + ' -j %s' % (concurrency) + ' profile-build', shell=True)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'make COMP=mingw ARCH=x86-64-modern -j 3 profile-build' returned non-zero exit status 1
Task exited

Any quick-fix?

**Comment by ddugovic** [comment]
When you run `make COMP=mingw ARCH=x86-64-modern -j 3 profile-build` on Stockfish, what happens?

**Comment by Nordlandia** [comment]
You mean if i create a "custom_make.bat" executeable with the text "make COMP=mingw ARCH=x86-64-modern -j 3 profile-build" cmd briefly start and close within 250 ms or so.

**Comment by ddugovic** [comment]
Ah, so we're on Windows... yes, from a command shell run that batch file in a folder containing the Stockfish project.  Even if it terminates the command shell should remain open and hopefully provide a meaningful error code and/or message.

**Comment by ianfab** [comment]
Yes, please post here which error is reported after execution of the bat file. If it closes automatically, https://stackoverflow.com/questions/13746177/batch-files-how-to-leave-the-console-window-open might help.

**Comment by Nordlandia** [comment]
Fixed it easily. Just by editing removing the brackets in " >fishtest.bat< " and update everything per manual. But the issue is still on the LGA775 machine 

Command 'make COMP=mingw ARCH=x86-64-modern -j 3

Another question is my new user is capped at 5-6 machines because i don't want to waste CPU time not used for nothing. So please raise my max number of machine currently contributing. Thanks.
