### ISSUE TITLE
make server python3 compatible

### ISSUE THREAD

**Issue by ppigazzini** [ianfab/fishtest#32]
First draft running on Ubuntu 20.04 with python 3.8.8 and latest mongodb, nginx etc.
https://github.com/ppigazzini/fishtest/tree/server_python3

Here is the setup script:
[setup_mvfishtest-wiki.txt](https://github.com/ianfab/fishtest/files/6217796/setup_mvfishtest-wiki.txt)

Here is the update script:
[update_mvfishtest.txt](https://github.com/ianfab/fishtest/files/6217320/update_mvfishtest.txt)

**Comment by ppigazzini** [comment]
@ianfab if you have a mongodb running with an old storage engine be sure to delete the *.json files from the "dump" folder before importing the backup in the mongodb running wiht the "WiredTiger" storage engine. This is the script used to update PROD from the old CentOS config https://github.com/glinscott/fishtest/issues/408

```
#!/bin/bash
# mongodb_restore.sh
# create a backup with:
# mongodump && tar -czvf dump.tar.gz dump && rm -rf dump

bkp_dir=${HOME}/backup/restore
[ ! -d ${bkp_dir} ] && mkdir -p ${bkp_dir}
mv dump.tar.gz ${bkp_dir}
cd ${bkp_dir}
mongo fishtest         --eval 'db.dropDatabase()'
mongo fishtest_new     --eval 'db.dropDatabase()'
mongo fishtest_testing --eval 'db.dropDatabase()'

tar -xzvf dump.tar.gz && rm -f dump/*/*.json && mongorestore --drop
```

**Comment by ianfab** [comment]
Thanks. I will try to make a test run of the migration in the next days to see if this is working fine.

**Comment by ppigazzini** [comment]
@ianfab folder code renamed "server" like in official, setup script updated in first post (fixed crontab)

**Comment by ppigazzini** [comment]
@ianfab the server has been running fine with python3 in the last 24 hours on my local testebed.
This morning I pushed a correction for `scavenge.py`.

I got this warnings with SPSA, I don't know if this is expected:

```
Warning: base doesn't have option PieceValue[MG][KNIGHT]
Warning: base doesn't have option PieceValue[MG][PAWN]
Warning: base doesn't have option PieceValue[MG][QUEEN]
Warning: base doesn't have option PieceValue[MG][ROOK]
Indexing opening suite...
Started game 1 of 6 (stockfish vs base)
Started game 2 of 6 (base vs stockfish)
Started game 3 of 6 (stockfish vs base)
```

**Comment by ianfab** [comment]
Thanks again, and sorry for the very long delay. I finally got to testing it, and since it looked good and the queue was empty I directly also upgraded the production server to 20.04 and applied the changes. Still need to do some cleanup, but it's running for now. Merged in https://github.com/ianfab/fishtest/pull/33.

**Comment by ppigazzini** [comment]
Updated wiki page with the new server setup script: 
https://github.com/ianfab/fishtest/wiki/Server-setup-on-Ubuntu

Please mind that the current `pyenv` requires a new `.profile` and `.bashrc` configuration:

- `.profile`:
```bash
# for ssh logins, install and configure the libpam-umask package.
#umask 022:

# pyenv: keep before sourcing .bashrc
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# if running bash
```

- `.bashrc`:
```bash
    . /etc/bash_completion
  fi
fi

# pyenv: keep at the end of the file
if command -v pyenv &>/dev/null; then
  eval "$(pyenv init -)"
fi
```
